### ISSUE TITLE
FC when clicking on the Add button in SlimActions

### ISSUE THREAD

**Issue by amspeople** [TeamBliss-LP/android_packages_apps_Settings#17]
If you click the Add button in settings - bliss interface - notification drawer - SlimActions, then we obtain a system crash, since we can't get the array size mActionConfigs for the reason that it is equal to null.
FC line: https://github.com/TeamBliss-LP/android_packages_apps_Settings/blob/lp5.1/src/com/android/settings/bliss/dslv/ActionListViewSettings.java#L457

Also, the system crash can be obtained if you click on the Add button in  settings - bliss interface - lock screen options - middle shortcuts. The cause of the error is the same.

**Comment by rxzcums** [comment]
thanks for your post, amspeople :+1:
