### ISSUE TITLE
Navigation Bar not work

### ISSUE THREAD

**Issue by rxzcums** [TeamBliss-LP/android_packages_apps_Settings#18]
Navigation Bar not work when press Hardware "home" key or Hardware "menu" key.
1. enable Navigation Bar: Settings - Bliss interface - Navigation options - Navigation Bar, "Enable navigation bar" turn on.
2. Disable Hardware Keys, can do by this way: Settings - Bliss interface - Notification drawer - Select and order tiles, choose "Add", choose "Hardware Keys", then can disable Hardware Keys from QS settings.
3. when Hardware "home" key or Hardware "menu" key is pressed, the Navigation Bar will not work.

please check & fix, thank you.
because when i hold the phone, sometimes make the Hardware "home" key or Hardware "menu" key pressed, so the problem disturb daily use.

**Comment by rxzcums** [comment]
in cm12.1, when enable Navigation Bar,  will automatic disable the Hardware Key compleletely, no this problem.

**Comment by amspeople** [comment]
In build from 12.06.15 occurs crash when enable navigation bar.
Else inactive range from multiple pixels at the bottom of the screen, which makes it inconvenient to use bottom buttons of the keyboard.
